/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import Modelo.Clientes;
import ReactivoLN.ClienteManejador;
import Utilidad.UtilX;
import java.awt.Color;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import org.kordamp.ikonli.fontawesome.FontAwesome;
import org.kordamp.ikonli.swing.FontIcon;
import raven.toast.Notifications;

/**
 *
 * @author IvanCS
 */
public class JIFClientes extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFClientes
     */
    public JIFClientes() {
        initComponents();
        modelo = (DefaultTableModel) jtbLista.getModel();
        UtilX.AsignarPlaceHolder(jtxfbuscar, "Ingrese cliente a buscar");
        jbtnbuscar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.FILTER), Color.white, 24));
        btninsertar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.PLUS_CIRCLE), Color.white, 24));
        jbtnactualizar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.EDIT), Color.white, 24));
        jbtneliminar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.REMOVE), Color.white, 24));

        jPanel1.setBackground(new Color(170, 219, 213));
        jPanel4.setBackground(new Color(234, 246, 245));
        jPanel3.setBackground(new Color(159, 231, 220));//lista

        //
        clienteManejador = new ClienteManejador(modelo);
        clienteManejador.subscribe(clienteManejador);// Suscribir a sí mismo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbLista = new javax.swing.JTable();
        jbtnactualizar = new javax.swing.JButton();
        btninsertar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtxfbuscar = new javax.swing.JTextField();
        jbtnbuscar = new javax.swing.JButton();
        jbtneliminar = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion Clientes");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lista de Clientes");
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jtbLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "DNI", "Genero", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbLista);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jbtnactualizar.setText("Actualizar");
        jbtnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnactualizarActionPerformed(evt);
            }
        });

        btninsertar.setText("Nuevo");
        btninsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninsertarActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel3.setText("Buscar por DNI:");

        jbtnbuscar.setText("Buscar");
        jbtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtxfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(jbtnbuscar)
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxfbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jbtnbuscar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jbtneliminar.setText("Eliminar");
        jbtneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtneliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btninsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbtnactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(jbtneliminar))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninsertar)
                    .addComponent(jbtnactualizar)
                    .addComponent(jbtneliminar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel modelo;
    List<Clientes> listaClientes;
    public static Clientes cliente;
    public static boolean estado;
    public static boolean resObtenido;
    public static ClienteManejador clienteManejador;

    //
    private void jbtnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnactualizarActionPerformed
        if (jtbLista.getSelectedRow() >= 0) {
            var indice = jtbLista.getSelectedRow();
            var id = Integer.parseInt(jtbLista.getValueAt(indice, 0).toString());
            var nombres = jtbLista.getValueAt(indice, 1).toString();
            var apellidos = jtbLista.getValueAt(indice, 2).toString();
            var dni = jtbLista.getValueAt(indice, 3).toString();
            var genero = jtbLista.getValueAt(indice, 4).toString();
            var direccion = jtbLista.getValueAt(indice, 5).toString();
            cliente = new Clientes(id, nombres, apellidos, dni, genero, direccion);
            estado = true;
            var jd = new JDClientesDatos(null, true);
            jd.setLocationRelativeTo(null);
            jd.setVisible(true);
            if (resObtenido) {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, JDClientesDatos.texto);
            }
        }
    }//GEN-LAST:event_jbtnactualizarActionPerformed

    private void btninsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninsertarActionPerformed
        estado = false;
        var jd = new JDClientesDatos(null, true);
        jd.setLocationRelativeTo(null);
        jd.setVisible(true);
        if (resObtenido) {
            Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, JDClientesDatos.texto);
        }
    }//GEN-LAST:event_btninsertarActionPerformed

    private void jbtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscarActionPerformed
        clienteManejador.ListarByDNI(jtxfbuscar.getText());
    }//GEN-LAST:event_jbtnbuscarActionPerformed

    private void jbtneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtneliminarActionPerformed
        if (jtbLista.getSelectedRow() >= 0) {
            var indice = jtbLista.getSelectedRow();
            var id = Integer.parseInt(jtbLista.getValueAt(indice, 0).toString());
            var nombres = jtbLista.getValueAt(indice, 1).toString();
            var apellidos = jtbLista.getValueAt(indice, 2).toString();
            var dni = jtbLista.getValueAt(indice, 3).toString();
            var genero = jtbLista.getValueAt(indice, 4).toString();
            var direccion = jtbLista.getValueAt(indice, 5).toString();
            cliente = new Clientes(id, nombres, apellidos, dni, genero, direccion);
            if (clienteManejador.Eliminar(cliente)) {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, JDClientesDatos.texto);
            }
        }
    }//GEN-LAST:event_jbtneliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninsertar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnactualizar;
    private javax.swing.JButton jbtnbuscar;
    private javax.swing.JButton jbtneliminar;
    private javax.swing.JTable jtbLista;
    private javax.swing.JTextField jtxfbuscar;
    // End of variables declaration//GEN-END:variables
}
