/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package UI;

import DAO.ReservasDAO;
import Modelo.Clientes;
import Modelo.DetalleReservas;
import Modelo.Habitaciones;
import Modelo.Reservas;
import ReactivoLN.DetalleReservaManejador;
import Utilidad.UtilX;
import java.awt.Color;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.kordamp.ikonli.fontawesome.FontAwesome;
import org.kordamp.ikonli.swing.FontIcon;
import raven.toast.Notifications;

/**
 *
 * @author IvanCS
 */
public class JIFReservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReservas
     */
    public JIFReservas() {
        initComponents();
        modelo = (DefaultTableModel) jtblista.getModel();
        jtxffecha.setText(LocalDate.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        //icono a botones
        jbtnbuscar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.FILTER), Color.white, 24));
        jbtnagregar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.PLUS), Color.white, 24));
        jbtnquitar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.REMOVE), Color.white, 24));
        jbtnguardar.setIcon(UtilX.setIconoX(FontIcon.of(FontAwesome.BOOK), Color.white, 24));
        //placer holdeer
        UtilX.AsignarPlaceHolder(jtxfcliente, "Busque un cliente");
        UtilX.AsignarPlaceHolder(jtxfduracion, "Ingrese nro de dias");
        //
        jPanel1.setBackground(new Color(170, 219, 213));
        jPanel2.setBackground(new Color(234, 246, 245));
        jPanel5.setBackground(new Color(234, 246, 245));
        jPanel4.setBackground(new Color(159, 231, 220));//lista reserva
        //
        detalleManejador = new DetalleReservaManejador(modelo, listaDetalle, jlbltotal);
        detalleManejador.subscribe(detalleManejador);// Suscribir a sí mismo
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxfcliente = new javax.swing.JTextField();
        jbtnbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxfduracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxffecha = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbtnagregar = new javax.swing.JButton();
        jbtnquitar = new javax.swing.JButton();
        jbtnguardar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblista = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jlbltotal = new javax.swing.JLabel();

        setClosable(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestion Reservas");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel2.setText("Cliente:");

        jtxfcliente.setEditable(false);

        jbtnbuscar.setText("buscar");
        jbtnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnbuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Duracion:");

        jLabel4.setText("Fecha:");

        jtxffecha.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnbuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxfduracion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jtxffecha, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxfcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnbuscar))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jtxffecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxfduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lista Reserva");
        jPanel4.add(jLabel5, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setPreferredSize(new java.awt.Dimension(90, 250));
        jPanel5.setLayout(new java.awt.GridLayout(5, 0, 0, 20));
        jPanel5.add(jLabel7);

        jbtnagregar.setToolTipText("Agregar");
        jbtnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnagregarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnagregar);

        jbtnquitar.setToolTipText("Quitar");
        jbtnquitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnquitarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnquitar);

        jbtnguardar.setToolTipText("Guardar");
        jbtnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnguardarActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnguardar);

        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_START);

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel6.setLayout(new java.awt.BorderLayout());

        jtblista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdHabitacion", "Nro Hab", "Descripcion", "Duracion", "Costo", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtblista);
        if (jtblista.getColumnModel().getColumnCount() > 0) {
            jtblista.getColumnModel().getColumn(0).setMinWidth(0);
            jtblista.getColumnModel().getColumn(0).setPreferredWidth(0);
            jtblista.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6, java.awt.BorderLayout.CENTER);

        jLabel6.setText("Total:");

        jlbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbltotal.setText("0.0");
        jlbltotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(jlbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jlbltotal))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel modelo;
    public static Clientes cliente;
    public static Habitaciones habitacion;
    static List<DetalleReservas> listaDetalle = new ArrayList<>();
    float total;
    private DetalleReservaManejador detalleManejador;

    private void jbtnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnbuscarActionPerformed
        var modal = new JDEnvioDTClientes(null, true);
        modal.setLocationRelativeTo(this);
        modal.setVisible(true);
        if (cliente != null) {
            jtxfcliente.setText(cliente.Nombres());
        }
    }//GEN-LAST:event_jbtnbuscarActionPerformed

    private void jbtnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnagregarActionPerformed
        var modal = new JDListaHabitaciones(new JFrame(), true);
        modal.setLocationRelativeTo(this);
        modal.setVisible(true);
        var duracion = Integer.parseInt(jtxfduracion.getText());
        if (habitacion != null && duracion > 0) {
            var detalle = new DetalleReservas(0, habitacion, duracion);
            detalleManejador.AgregarElemento(detalle);
        }
    }//GEN-LAST:event_jbtnagregarActionPerformed

    private void jbtnquitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnquitarActionPerformed
        if (jtblista.getSelectedRow() >= 0) {
            var indice = jtblista.getSelectedRow();
            var id = Integer.parseInt(jtblista.getValueAt(indice, 0).toString());
            var detalle = new DetalleReservas(0, new Habitaciones(id, "", "", 0), 0);
            detalleManejador.QuitarElemento(detalle);
        }
    }//GEN-LAST:event_jbtnquitarActionPerformed

    private void jbtnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnguardarActionPerformed
        if (cliente != null && !listaDetalle.isEmpty()) {
            var fecha = LocalDate.parse(jtxffecha.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy"));
            var duracion = Integer.parseInt(jtxfduracion.getText());
            var reserva = new Reservas(0, cliente, fecha, duracion, "", listaDetalle);
            if (detalleManejador.GuardarReserva(reserva)) {
                Notifications.getInstance().show(Notifications.Type.SUCCESS, Notifications.Location.TOP_CENTER, "Reserva Guardada!");
                detalleManejador.LimpiarElementos();
                jtxfcliente.setText("");
                jtxfduracion.setText("");
                jlbltotal.setText("0.00");
            }
        }
    }//GEN-LAST:event_jbtnguardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnagregar;
    private javax.swing.JButton jbtnbuscar;
    private javax.swing.JButton jbtnguardar;
    private javax.swing.JButton jbtnquitar;
    private javax.swing.JLabel jlbltotal;
    private javax.swing.JTable jtblista;
    private javax.swing.JTextField jtxfcliente;
    private javax.swing.JTextField jtxfduracion;
    private javax.swing.JTextField jtxffecha;
    // End of variables declaration//GEN-END:variables
}
