/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.TallerAPP01;

import UI.JFPrincipal;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.UIManager;



public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        try {
            /*
        
            UIManager.put("RootPane.background", new Color(234, 246, 245));
            UIManager.put("Button.background", new Color(57, 173, 173));
            UIManager.put("Button.foreground", new Color(255, 255, 255));
            UIManager.put("Button.arc", 999);
            UIManager.put("TextComponent.arc", 999);
            UIManager.put("Table.background", new Color(234, 246, 245));
            UIManager.put("Table.selectionBackground", new Color(57, 173, 173));
            UIManager.put("TableHeader.background", new Color(186, 244, 238));
            UIManager.put("TableHeader.foreground", new Color(0, 0, 0));

            UIManager.put("MenuBar.selectionBackground", new Color(140, 235, 235));
            UIManager.put("MenuItem.background", new Color(84, 81, 214));
            UIManager.put("MenuItem.selectionBackground", new Color(108, 211, 188));
            */
            FlatLaf.registerCustomDefaultsSource("Theme");
            UIManager.setLookAndFeel(new FlatLightLaf());
            var gui= new JFPrincipal();
            gui.setExtendedState(JFrame.MAXIMIZED_BOTH);
            gui.setVisible(true);
        } catch (Exception e) {
        }
    }
}
